stages:
  - build
  - deploy

# job to deploy the public facing website
# Full project: https://gitlab.com/pages/plain-html
pages:
    stage: deploy
    script:
        - mkdir .public
        - cp -r documentation/public-website public
    artifacts:
        paths:
            - public
    only:
        - master

build_pm_frontend:
    stage: build
    image: node:latest
    script:
        - cd apps/project-idea-manager/frontend
        - npm install --production --no-progress
        - npm run build
    only:
        changes:
          - "apps/project-idea-manager/frontend"

